services:
  backend:
    image: python:3.9-slim
    working_dir: /app
    # Install deps then launch server; requirements.txt lives inside mounted /app directory
    command: >
      sh -c "set -e
      echo 'Installing system dependencies for PostgreSQL...';
      apt-get update && apt-get install -y gcc libpq-dev postgresql-client;
      echo 'Installing Python dependencies...';
      if [ ! -f requirements.txt ]; then echo 'requirements.txt not found in /app'; ls -al; exit 1; fi;
      pip install --upgrade pip;
      pip install --no-cache-dir -r requirements.txt;
      echo 'Starting Flask server...';
      PYTHONUNBUFFERED=1 python run_server.py"
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      # Ensure the backend connects to the Postgres container, not localhost
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-edgar_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      # Override DATABASE_URL from .env so container uses service host 'db'
      - DATABASE_URL=${DATABASE_URL_COMPOSE}
      - JWT_SECRET=${JWT_SECRET:-test-secret}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEFAULT_TEST_TENANT=${DEFAULT_TEST_TENANT:-00000000-0000-0000-0000-000000000001}
      # Development authentication bypass
      - DEV_NO_AUTH=true
      - BYPASS_TENANT_ISOLATION=true
      - SKIP_TENANT_ENFORCEMENT=true
      - FALLBACK_TO_MEMORY=false
      # Enable E2E bypass logic in backend auth/tenant middleware
      - APP_INSTANCE_ID=ci
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_DOCKER_ENV=true
      - VITE_NODE_ENV=production
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_password}
      POSTGRES_DB: ${POSTGRES_DB:-test_autoshop}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-edgar_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
