services:
  backend:
    image: python:3.9-slim
    working_dir: /app
    # Install deps then launch server; requirements.txt lives inside mounted /app directory
    command: >
      sh -c "set -e
      echo 'Installing system dependencies for PostgreSQL...';
      apt-get update && apt-get install -y gcc libpq-dev;
      echo 'Installing Python dependencies...';
      if [ ! -f requirements.txt ]; then echo 'requirements.txt not found in /app'; ls -al; exit 1; fi;
      pip install -r requirements.txt || { echo 'Pip install failed - check requirements.txt'; exit 1; };
      echo 'Starting Flask server...';
      PYTHONUNBUFFERED=1 python run_server.py"
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEFAULT_TEST_TENANT=${DEFAULT_TEST_TENANT}
      - APP_INSTANCE_ID=${APP_INSTANCE_ID}
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_DOCKER_ENV=true
      - VITE_NODE_ENV=production
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
