-- AUTO-GENERATED: seed_v2_catalog.sql
BEGIN;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'OIL_SYNTH',
  'Full Synthetic Oil Change',
  'MAINTENANCE',
  0.30,
  0.50,
  0.75,
  120.00,
  false,
  1,
  '{ALL}',
  '{"oil", "synthetic", "filter"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'OIL_CONV',
  'Conventional Oil Change',
  'MAINTENANCE',
  0.25,
  0.40,
  0.65,
  100.00,
  false,
  1,
  '{ALL}',
  '{"oil", "conventional", "filter"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'OIL_HIGH_MILE',
  'High‑Mileage Oil Change',
  'MAINTENANCE',
  0.30,
  0.50,
  0.75,
  130.00,
  false,
  1,
  '{ALL}',
  '{"oil", "high‑mileage", "seal"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'TIRE_ROTATION',
  'Tire Rotation (FWD/RWD)',
  'MAINTENANCE',
  0.30,
  0.50,
  0.75,
  35.00,
  false,
  1,
  '{ALL}',
  '{"tire", "rotation"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'TIRE_ROTATION_AWD',
  'Tire Rotation (AWD)',
  'MAINTENANCE',
  0.45,
  0.75,
  1.05,
  50.00,
  false,
  2,
  '{ALL}',
  '{"tire", "rotation", "awd"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'MULTI_POINT_INSPECTION',
  'Multi‑Point Inspection',
  'MAINTENANCE',
  0.25,
  0.25,
  0.50,
  0.00,
  false,
  1,
  '{ALL}',
  '{"inspection", "checkup"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'AIR_FILTER_REPLACE',
  'Engine Air Filter Replacement',
  'MAINTENANCE',
  0.25,
  0.20,
  0.45,
  25.00,
  false,
  1,
  '{ALL}',
  '{"filter", "engine"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CABIN_FILTER_REPLACE',
  'Cabin Air Filter Replacement',
  'MAINTENANCE',
  0.25,
  0.30,
  0.55,
  30.00,
  false,
  1,
  '{ALL}',
  '{"filter", "cabin"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'WIPER_BLADE_REPLACE',
  'Wiper Blade Replacement (Pair)',
  'MAINTENANCE',
  0.25,
  0.20,
  0.45,
  15.00,
  false,
  1,
  '{ALL}',
  '{"wiper", "visibility"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'BATTERY_TEST_INSTALL',
  'Battery Test & Install',
  'ELECTRICAL_BATTERY',
  0.25,
  0.30,
  0.55,
  35.00,
  false,
  1,
  '{ALL}',
  '{"battery", "test", "install"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'BRAKE_INSPECTION',
  'Brake Inspection (Comprehensive)',
  'BRAKES',
  0.30,
  0.50,
  0.75,
  0.00,
  false,
  2,
  '{ALL}',
  '{"brake", "safety", "inspection"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'PADS_ROTORS_FRONT',
  'Front Brake Pads & Rotors',
  'BRAKES',
  1.20,
  2.00,
  2.80,
  260.00,
  false,
  2,
  '{ALL}',
  '{"brake", "pads", "rotors", "front"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'PADS_ROTORS_REAR',
  'Rear Brake Pads & Rotors',
  'BRAKES',
  1.32,
  2.20,
  3.08,
  280.00,
  false,
  2,
  '{ALL}',
  '{"brake", "pads", "rotors", "rear"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'BRAKE_FLUID_FLUSH',
  'Brake Fluid Flush',
  'BRAKES',
  0.60,
  1.00,
  1.40,
  130.00,
  false,
  2,
  '{ALL}',
  '{"brake", "fluid", "flush"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CALIPER_REPLACE_FRONT',
  'Front Caliper Replacement (Single)',
  'BRAKES',
  0.60,
  1.00,
  1.40,
  140.00,
  false,
  3,
  '{ALL}',
  '{"caliper", "hydraulics"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CHECK_ENGINE_DIAG_BASIC',
  'Check Engine Light Diagnostic (Basic)',
  'ENGINE_DIAGNOSTICS',
  0.60,
  1.00,
  1.40,
  110.00,
  false,
  2,
  '{ALL}',
  '{"obd2", "cel", "codes"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CHECK_ENGINE_DIAG_ADVANCED',
  'Advanced Engine Diagnostics',
  'ENGINE_DIAGNOSTICS',
  1.20,
  2.00,
  2.80,
  150.00,
  true,
  4,
  '{ALL}',
  '{"scope", "compression", "advanced"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'NO_START_DIAG',
  'No‑Start Diagnostic',
  'ENGINE_DIAGNOSTICS',
  1.20,
  2.00,
  2.80,
  160.00,
  true,
  4,
  '{ALL}',
  '{"no‑start", "electrical", "fuel"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ATF_DRAIN_FILL',
  'Automatic Transmission Drain & Fill',
  'TRANSMISSION_DRIVETRAIN',
  0.60,
  1.00,
  1.40,
  135.00,
  false,
  2,
  '{ALL}',
  '{"transmission", "atf", "service"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ATF_FLUSH',
  'Automatic Transmission Flush',
  'TRANSMISSION_DRIVETRAIN',
  0.90,
  1.50,
  2.10,
  145.00,
  false,
  3,
  '{ALL}',
  '{"transmission", "flush"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CVT_SERVICE',
  'CVT Transmission Service',
  'TRANSMISSION_DRIVETRAIN',
  1.20,
  2.00,
  2.80,
  180.00,
  true,
  4,
  '{ALL}',
  '{"cvt", "fluid", "service"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'MANUAL_TRANS_FLUID',
  'Manual Transmission Fluid Service',
  'TRANSMISSION_DRIVETRAIN',
  0.45,
  0.75,
  1.05,
  120.00,
  false,
  2,
  '{ALL}',
  '{"manual", "gear oil"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'FOUR_WHEEL_ALIGNMENT',
  'Four‑Wheel Alignment',
  'TIRES_STEERING_SUSPENSION',
  0.75,
  1.25,
  1.75,
  150.00,
  false,
  3,
  '{ALL}',
  '{"alignment", "tire wear", "pull"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'STRUT_ASSEMBLY_FRONT_PAIR',
  'Front Strut Assembly (Pair)',
  'TIRES_STEERING_SUSPENSION',
  1.50,
  2.50,
  3.50,
  145.00,
  false,
  3,
  '{ALL}',
  '{"struts", "suspension"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'CONTROL_ARM_REPLACE_FRONT',
  'Front Control Arm Replacement',
  'TIRES_STEERING_SUSPENSION',
  1.20,
  2.00,
  2.80,
  160.00,
  false,
  3,
  '{ALL}',
  '{"control arm", "bushings"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'SWAY_BAR_LINKS_PAIR',
  'Sway Bar Link Replacement (Pair)',
  'TIRES_STEERING_SUSPENSION',
  0.60,
  1.00,
  1.40,
  110.00,
  false,
  2,
  '{ALL}',
  '{"sway bar", "links"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'AC_RECHARGE_R1234YF',
  'A/C Recharge (R‑1234yf)',
  'HVAC',
  0.60,
  1.00,
  1.40,
  160.00,
  false,
  3,
  '{ALL}',
  '{"ac", "recharge", "r1234yf"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'AC_EVAP_CORE_CLEAN',
  'Evaporator Core Clean & Deodorize',
  'HVAC',
  0.90,
  1.50,
  2.10,
  120.00,
  false,
  2,
  '{ALL}',
  '{"ac", "evaporator", "odor"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'BATTERY_REPLACE_GRP35',
  'Battery Replacement (Group 35)',
  'ELECTRICAL_BATTERY',
  0.30,
  0.50,
  0.75,
  40.00,
  false,
  2,
  '{ALL}',
  '{"battery", "install"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ALTERNATOR_REPLACE',
  'Alternator Replacement',
  'ELECTRICAL_BATTERY',
  1.20,
  2.00,
  2.80,
  180.00,
  false,
  3,
  '{ALL}',
  '{"alternator", "charging"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'STARTER_REPLACE',
  'Starter Replacement',
  'ELECTRICAL_BATTERY',
  0.90,
  1.50,
  2.10,
  170.00,
  false,
  3,
  '{ALL}',
  '{"starter", "cranking"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'HEADLIGHT_RESTORE',
  'Headlight Lens Restoration (Pair)',
  'ELECTRICAL_BATTERY',
  0.60,
  1.00,
  1.40,
  100.00,
  false,
  1,
  '{ALL}',
  '{"headlight", "restore"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'COOLANT_FLUSH',
  'Cooling System Flush & Fill',
  'COOLING_SYSTEM',
  0.90,
  1.50,
  2.10,
  130.00,
  false,
  2,
  '{ALL}',
  '{"coolant", "flush", "radiator"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'RADIATOR_REPLACE',
  'Radiator Replacement',
  'COOLING_SYSTEM',
  1.50,
  2.50,
  3.50,
  140.00,
  false,
  3,
  '{ALL}',
  '{"radiator", "leak", "overheat"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'WATER_PUMP_REPLACE_I4',
  'Water Pump Replacement (I4)',
  'COOLING_SYSTEM',
  1.80,
  3.00,
  4.20,
  180.00,
  false,
  3,
  '{ALL}',
  '{"water pump", "coolant"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ADAS_CAMERA_CALIB_STATIC',
  'Static Front Camera Calibration',
  'ADAS',
  0.90,
  1.50,
  2.10,
  190.00,
  true,
  5,
  '{ALL}',
  '{"adas", "camera", "calibration"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ADAS_RADAR_CALIB_STATIC',
  'Static ACC Radar Calibration',
  'ADAS',
  0.60,
  1.00,
  1.40,
  190.00,
  true,
  5,
  '{ALL}',
  '{"adas", "radar", "calibration"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ADAS_CAMERA_CALIB_DYNAMIC',
  'Dynamic Camera Calibration (LDW)',
  'ADAS',
  0.60,
  1.00,
  1.40,
  150.00,
  true,
  4,
  '{ALL}',
  '{"adas", "dynamic", "ldw"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'ECU_TUNE_STAGE1_VAG',
  'Stage 1 ECU Performance Tune (VW/Audi)',
  'INSPECTION_SAFETY',
  1.20,
  2.00,
  2.80,
  250.00,
  true,
  5,
  '{ALL}',
  '{"ecu", "tune", "remap"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'PRE_PURCHASE_INSPECTION',
  'Pre‑Purchase Inspection',
  'INSPECTION_SAFETY',
  0.90,
  1.50,
  2.10,
  150.00,
  false,
  3,
  '{ALL}',
  '{"ppi", "inspection"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'SMOG_PRECHECK',
  'Smog Pre‑Check (Non‑cert)',
  'INSPECTION_SAFETY',
  0.30,
  0.50,
  0.75,
  65.00,
  false,
  2,
  '{ALL}',
  '{"smog", "precheck"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'TIMING_BELT_WP_V6_HONDA',
  'Timing Belt & Water Pump (Honda V6)',
  'ENGINE_DIAGNOSTICS',
  2.70,
  4.50,
  6.30,
  800.00,
  true,
  4,
  '{ALL}',
  '{"timing belt", "water pump", "j‑series"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'SPARK_PLUGS_I4',
  'Spark Plug Replacement (I4)',
  'ENGINE_DIAGNOSTICS',
  0.90,
  1.50,
  2.10,
  160.00,
  false,
  2,
  '{ALL}',
  '{"spark plugs", "tune‑up"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'IGNITION_COILS_I4',
  'Ignition Coil Replacement (I4)',
  'ENGINE_DIAGNOSTICS',
  0.60,
  1.00,
  1.40,
  140.00,
  false,
  2,
  '{ALL}',
  '{"ignition coils", "misfire"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'FUEL_SYSTEM_CLEAN',
  'Fuel System Cleaning',
  'ENGINE_DIAGNOSTICS',
  0.60,
  1.00,
  1.40,
  120.00,
  false,
  2,
  '{ALL}',
  '{"fuel", "injector", "clean"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'INTAKE_CARBON_CLEAN_GDI',
  'Intake Valve Carbon Clean (GDI)',
  'ENGINE_DIAGNOSTICS',
  1.20,
  2.00,
  2.80,
  220.00,
  false,
  3,
  '{ALL}',
  '{"walnut blast", "intake", "gdi"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'REAR_DIFF_SERVICE',
  'Rear Differential Fluid Service',
  'TRANSMISSION_DRIVETRAIN',
  0.45,
  0.75,
  1.05,
  120.00,
  false,
  2,
  '{ALL}',
  '{"differential", "gear oil"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'TRANSFER_CASE_SERVICE',
  'Transfer Case Service',
  'TRANSMISSION_DRIVETRAIN',
  0.60,
  1.00,
  1.40,
  130.00,
  false,
  2,
  '{ALL}',
  '{"transfer case", "fluid"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'AXLE_CV_REPLACE_FRONT',
  'Front CV Axle Replacement (Single)',
  'TRANSMISSION_DRIVETRAIN',
  1.20,
  2.00,
  2.80,
  220.00,
  false,
  3,
  '{ALL}',
  '{"cv axle", "clicking"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
INSERT INTO service_operations (
  id,
  name,
  category,
  min_hours,
  typical_hours,
  max_hours,
  base_labor_rate,
  requires_senior_tech,
  skill_level,
  vehicle_types,
  keywords,
  is_active
) VALUES (
  'PCV_VALVE_REPLACE',
  'PCV Valve Replacement',
  'MAINTENANCE',
  0.36,
  0.60,
  0.85,
  90.00,
  false,
  2,
  '{ALL}',
  '{"pcv", "valve", "emissions"}',
  true
) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, min_hours = EXCLUDED.min_hours, typical_hours = EXCLUDED.typical_hours, max_hours = EXCLUDED.max_hours, base_labor_rate = EXCLUDED.base_labor_rate, requires_senior_tech = EXCLUDED.requires_senior_tech, skill_level = EXCLUDED.skill_level, vehicle_types = EXCLUDED.vehicle_types, keywords = EXCLUDED.keywords, is_active = EXCLUDED.is_active;
COMMIT;
