name: Accessibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Nightly accessibility tests at 02:00 UTC (T-016 follow-up - Exit Criteria #6)
    - cron: '0 2 * * *'

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run accessibility tests
      id: a11y-tests
      run: |
        cd frontend
        echo "♿ Running WCAG 2.2 AA accessibility tests..."
        npm run test:a11y

    - name: Generate accessibility reports
      if: always()
      run: |
        cd frontend
        echo "📊 Generating detailed accessibility reports..."
        # Generate junit report for CI integration
        npm run test:a11y -- --reporter=junit --outputFile=accessibility-junit.xml || true
        # Generate verbose report for detailed analysis
        npm run test:a11y -- --reporter=verbose > accessibility-detailed.txt 2>&1 || true
        # Create HTML report summary
        echo "<!DOCTYPE html><html><head><title>Accessibility Test Report</title></head><body>" > accessibility-report.html
        echo "<h1>WCAG 2.2 AA Accessibility Test Report</h1>" >> accessibility-report.html
        echo "<p>Generated on: $(date -u)</p>" >> accessibility-report.html
        echo "<h2>Test Results</h2>" >> accessibility-report.html
        echo "<pre>" >> accessibility-report.html
        cat accessibility-detailed.txt >> accessibility-report.html
        echo "</pre></body></html>" >> accessibility-report.html

    - name: Upload a11y-report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: a11y-report
        path: |
          frontend/accessibility-junit.xml
          frontend/accessibility-detailed.txt
          frontend/accessibility-report.html
        retention-days: 30

    - name: Nightly report summary
      if: github.event_name == 'schedule'
      run: |
        echo "🌙 Nightly Accessibility Test Summary"
        echo "====================================="
        echo "Scheduled run completed at $(date -u)"
        echo "Reports uploaded as 'a11y-report' artifact"
        echo "Retention: 30 days"
        if [ "${{ steps.a11y-tests.outcome }}" == "success" ]; then
          echo "✅ All accessibility tests passed"
        else
          echo "⚠️ Some accessibility issues detected - check artifact for details"
        fi
