name: Auto Tag (manual)

on:
  workflow_dispatch:
    inputs:
      bump:
        description: bump type (patch/minor/major)
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute next tag
        id: bump
        run: |
          git fetch --tags --quiet
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          ver=${LAST_TAG#v}
          IFS='.' read -r MA MI PA <<< "$ver"
          case "${{ inputs.bump }}" in
            major) MA=$((MA+1)); MI=0; PA=0;;
            minor) MI=$((MI+1)); PA=0;;
            patch|*) PA=$((PA+1));;
          esac
          echo "new_tag=v$MA.$MI.$PA" >> $GITHUB_OUTPUT
      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "${{ steps.bump.outputs.new_tag }}" -m "release: ${{ steps.bump.outputs.new_tag }}"
          git push origin "${{ steps.bump.outputs.new_tag }}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
