name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Lint & Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'
      - name: Terraform Format
        working-directory: infrastructure
        run: terraform fmt -check
      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init
      - name: Terraform Validate
        working-directory: infrastructure
        run: terraform validate
      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan -out=tfplan

  deploy_and_smoke:
    name: Deploy & Smoke Tests
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        env: [ dev, staging, prod ]
    env:
      AWS_REGION: us-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve -var="env=${{ matrix.env }}"
      - name: Deploy Auth Lambda
        run: |
          cd scripts
          bash deploy_auth_lambda.sh latest
      - name: Deploy Profile Lambda
        run: |
          cd scripts
          bash deploy_profile_lambda.sh ${{ matrix.env }} latest
      - name: Smoke Test Auth Endpoints
        run: |
          cd scripts
          bash test_auth_endpoints.sh
      - name: Smoke Test Profile Endpoints
        run: |
          cd scripts
          bash test_profile_endpoints.sh
