name: Frontend Build

on:
  push:
    branches:
      - main
      - fix/**
      - feature/**
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build


