name: Optional Legacy Tests

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'services/**'
      - 'catalog_seed/**'
      - '.github/workflows/legacy-tests.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - 'services/**'
      - 'catalog_seed/**'
      - '.github/workflows/legacy-tests.yml'
  workflow_dispatch: {}

jobs:
  legacy-tests:
    runs-on: ubuntu-latest
    continue-on-error: true  # non-blocking
    if: |
      github.event_name != 'pull_request' ||
      contains(github.event.pull_request.labels.*.name, 'run-legacy-tests') ||
      true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run full pytest (allow failures)
        run: |
          pytest -q --junitxml=junit.xml || true
      - name: Upload junit (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: legacy-junit.xml
          path: junit.xml
          if-no-files-found: ignore
