name: Nightly Lint Debt

on:
  schedule:
    - cron: "0 9 * * *"  # daily 09:00 UTC
  workflow_dispatch: {}

jobs:
  ruff-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install ruff only
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run full-repo ruff (allow failures; bypass project excludes)
        id: ruff
        continue-on-error: true
        run: |
          ruff --version
          ruff check . --config .ruff-full.toml --output-format grouped > ruff_report.txt || true
      - name: Summarize
        run: |
          echo "Issues:" $(wc -l < ruff_report.txt || echo 0)
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ruff_report.txt
          path: ruff_report.txt
