name: Release Seed (on tag)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Generate seed (pretty + upsert)
        run: catalog-seed --csv backend/catalog_seed/service_catalog_master.csv --out seed_v2_catalog.sql --schema minimal --pretty --upsert

      - name: Upload seed artifact
        uses: actions/upload-artifact@v4
        with:
          name: seed_v2_catalog.sql
          path: seed_v2_catalog.sql

      - name: Create GitHub Release and attach seed
        uses: softprops/action-gh-release@v2
        with:
          files: seed_v2_catalog.sql
          generate_release_notes: true
